### ISSUE TITLE
deflate64 not supported correctly?

### ISSUE THREAD

**Issue by krab** [satoren/picounzip#6]
Ive created zip archive for peazip_portable-7.3.2.WIN64 using 7zip with deflate64 method. Picounzip extracts only single file from it.

**Comment by satoren** [comment]
Currently supported only store and deflate.
https://github.com/satoren/picounzip/blob/master/include/picounzip.hpp#L52

It doesn't support zlib either, so there is no hope of supporting it so far.
https://zlib.net/zlib_faq.html#faq40

**Comment by krab** [comment]
hm, 7zip somehow supports deflate64 even its "proprietary". (╯°□°）╯︵ ┻━┻

"mirror" repository link https://github.com/fred9/7z-src/blob/master/CPP/7zip/Compress/DeflateDecoder.cpp#L108
